### ISSUE TITLE
Idea: Certain name for chicken

### ISSUE THREAD

**Issue by StoopidMeap** [Pwn9/PwnChickenLay#1]
For my purposes, I need a specific name for a chicken (color coded) and for the thing layed specific to that chicken.

For example,

All chickens that are named "&bDiamond Chicken" will lay diamonds, but normal chickens will not lay these diamonds because they are not named "&bDiamond Chicken"

This would be a great feature 😀

**Comment by msudol** [comment]
That's interesting. I'll investigate if it is possible to get the chicken that spawned the event, and then check the meta of the entity to see if it has a specific name.  

Question for you:  Would a named chicken override per-biome settings?

**Comment by StoopidMeap** [comment]
Not sure, but thanks for looking into it :D

**Comment by msudol** [comment]
I know it's been awhile but I think I might have something coming down the pipe for this... it's not ready yet but soon.

**Comment by msudol** [comment]
https://github.com/Pwn9/PwnChickenLay/commit/c36db04ca73f7261b81851f7736cd5f68c3f8df9 - done!
