### ISSUE TITLE
spawn eggs dont work

### ISSUE THREAD

**Issue by jordanwilliams1** [Pwn9/PwnChickenLay#2]
when i try to use cow_spawn_egg i get an error..

is it still using 1.12 api?
https://i.gyazo.com/284731915ddc195526fc28a0bada72e6.png

**Comment by msudol** [comment]
Yes, looks like it is still using 1.12 api.

**Comment by msudol** [comment]
https://github.com/Pwn9/PwnChickenLay/releases/tag/v1.9 should resolve the issue.

**Comment by jordanwilliams1** [comment]
@msudol This did resolve the issue :) I Did this after I posted it. I Also discovered a bug in the code causing lore/names not to be saved on items #3 

Thanks for updating the GitHub.
